# Generated by Django 4.2.2 on 2024-03-22 00:25

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_groups(apps, schema_editor):
    creator_group = Group.objects.create(name="Creator")
    add_task_permission = Permission.objects.get(codename="add_task")
    creator_group.permissions.add(add_task_permission)
    editor_group = Group.objects.create(name="Editor")
    change_task_permission = Permission.objects.get(codename="change_task")
    editor_group.permissions.add(change_task_permission)
    admin_group = Group.objects.create(name="Admin")
    all_permissions = Permission.objects.filter(content_type__app_label='tasks')
    admin_group.permissions.set(all_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20240321_1225'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
