# Generated by Django 4.2.2 on 2024-03-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20240321_2125'),
    ]

    operations = [
    ]
