# Generated by Django 4.2.2 on 2024-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_epic_tasks_sprint_epic'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='task',
            table_comment=None,
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('status', 'UNASSIGNED'), ('status', 'IN_PROGRESS'), ('status', 'DONE'), ('status', 'ARCHIVED'), _connector='OR'), name='status_check'),
        ),
    ]
