# Generated by Django 4.2.2 on 2024-03-31 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_alter_task_table_comment_task_status_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='completion_status',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Completed'), ('ARCHIVED', 'Archived')], default='UNASSIGNED', max_length=20),
        ),
    ]
